title: Recognizing Illegible Handwriting
description: By Khoi Nguyen, Alex Clinton, Zhuoming Liu, and Thomas Zeng
google_analytics:
theme: jekyll-theme-cayman
github:
  is_project_page: true
  repository_url: https://github.com/mtzig/badwriting_OCR