plugins:
  - jekyll-relative-links
# theme: minima
theme: jekyll-theme-cayman
relative_links:
  enabled: true
  collections: true
title: Recognizing Illegible Handwriting
description: By Khoi Nguyen, Alex Clinton, Zhuoming Liu, and Thomas Zeng
github:
  repository_url: https://github.com/mtzig/badwriting_OCR
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
