plugins:
  - jekyll-relative-links
theme: minima
relative_links:
  enabled: true
  collections: true
title: Recognizing Illegible Handwriting
authors: alex,
header_pages:
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
